--------------------------------------------------------
-- Archivo creado  - martes-marzo-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALOJAMIENTOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304A461810"."ALOJAMIENTOS" 
   (	"IDALOJAMIENTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"IDOPERADOR" NUMBER, 
	"TIPO" VARCHAR2(20 BYTE), 
	"AMOBLADO" CHAR(1 BYTE), 
	"UBICACION" VARCHAR2(20 BYTE), 
	"COSTODIA" NUMBER, 
	"CAPACIDAD" NUMBER, 
	"TAMANIO" VARCHAR2(20 BYTE), 
	"COMPARTIDA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index ALOJAMIENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304A461810"."ALOJAMIENTOS_PK" ON "ISIS2304A461810"."ALOJAMIENTOS" ("IDALOJAMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  Constraints for Table ALOJAMIENTOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304A461810"."ALOJAMIENTOS" MODIFY ("COMPARTIDA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."ALOJAMIENTOS" MODIFY ("AMOBLADO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."ALOJAMIENTOS" MODIFY ("IDOPERADOR" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."ALOJAMIENTOS" MODIFY ("IDALOJAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."ALOJAMIENTOS" ADD CONSTRAINT "ALOJAMIENTOS_PK" PRIMARY KEY ("IDALOJAMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304A461810"."ALOJAMIENTOS" ADD CONSTRAINT "ALOJAMIENTOS_CHK3" CHECK (COSTODIA>=0 AND CAPACIDAD>=0 AND TAMANIO>=0) ENABLE;
  ALTER TABLE "ISIS2304A461810"."ALOJAMIENTOS" ADD CONSTRAINT "ALOJAMIENTOS_CHK2" CHECK (AMOBLADO = 'V' OR AMOBLADO = 'F'
AND 
COMPARTIDA = 'V' OR COMPARTIDA= 'F') ENABLE;
  ALTER TABLE "ISIS2304A461810"."ALOJAMIENTOS" ADD CONSTRAINT "ALOJAMIENTOS_CHK1" CHECK (TIPO = 'habitacion' OR TIPO = 'apartamento' OR TIPO = 'vivienda') ENABLE;
