--------------------------------------------------------
-- Archivo creado  - martes-marzo-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTRATOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304A461810"."CONTRATOS" 
   (	"IDCONTRATO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"FECHAINICIO" DATE, 
	"FECHAFIN" DATE, 
	"COSTOTOTAL" NUMBER, 
	"IDALOJAMIENTO" NUMBER, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"IDOPERADOR" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index CONTRATOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304A461810"."CONTRATOS_PK" ON "ISIS2304A461810"."CONTRATOS" ("IDCONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  Constraints for Table CONTRATOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304A461810"."CONTRATOS" MODIFY ("IDOPERADOR" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."CONTRATOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."CONTRATOS" MODIFY ("IDALOJAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."CONTRATOS" MODIFY ("IDCONTRATO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."CONTRATOS" ADD CONSTRAINT "CONTRATOS_PK" PRIMARY KEY ("IDCONTRATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304A461810"."CONTRATOS" ADD CONSTRAINT "CONTRATOS_CHK2" CHECK (COSTOTOTAL>=0) ENABLE;
  ALTER TABLE "ISIS2304A461810"."CONTRATOS" ADD CONSTRAINT "CONTRATOS_CHK1" CHECK (ESTADO = 'reserva' or ESTADO = 'cancelado' or ESTADO = 'activo' or ESTADO = 'vencido') ENABLE;
