--------------------------------------------------------
-- Archivo creado  - martes-marzo-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OPERADORES
--------------------------------------------------------

  CREATE TABLE "ISIS2304A461810"."OPERADORES" 
   (	"IDOPERADOR" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"TIPOOPERADOR" VARCHAR2(20 BYTE), 
	"REGISTROCC" VARCHAR2(20 BYTE), 
	"REGISTROSI" VARCHAR2(20 BYTE), 
	"VINCULO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304A461810"."TABLE1_PK" ON "ISIS2304A461810"."OPERADORES" ("IDOPERADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  Constraints for Table OPERADORES
--------------------------------------------------------

  ALTER TABLE "ISIS2304A461810"."OPERADORES" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("IDOPERADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304A461810"."OPERADORES" MODIFY ("IDOPERADOR" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."OPERADORES" ADD CONSTRAINT "OPERADORES_CHK2" CHECK (VINCULO IN ('estudiante', 'profesor', 'egresado', 'padre', 'profVinculado', 'visitante', 'otro' )) ENABLE;
  ALTER TABLE "ISIS2304A461810"."OPERADORES" ADD CONSTRAINT "OPERADORES_CHK1" CHECK (TIPOOPERADOR IN ('hotel', 'hostal', 'empresaVivienda','personaNat')) ENABLE;
