--------------------------------------------------------
-- Archivo creado  - martes-marzo-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROMOCIONES
--------------------------------------------------------

  CREATE TABLE "ISIS2304A461810"."PROMOCIONES" 
   (	"IDPROMOCION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"PRECIO" NUMBER, 
	"NUMDIAS" NUMBER, 
	"IDALOJAMIENTO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PROMOCIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304A461810"."PROMOCIONES_PK" ON "ISIS2304A461810"."PROMOCIONES" ("IDPROMOCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  Constraints for Table PROMOCIONES
--------------------------------------------------------

  ALTER TABLE "ISIS2304A461810"."PROMOCIONES" MODIFY ("IDALOJAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."PROMOCIONES" MODIFY ("IDPROMOCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304A461810"."PROMOCIONES" ADD CONSTRAINT "PROMOCIONES_PK" PRIMARY KEY ("IDPROMOCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304A461810"."PROMOCIONES" ADD CONSTRAINT "PROMOCIONES_CHK1" CHECK (PRECIO>=0) ENABLE;
