insert into CONTRATOSCLIENTES (IDCONTRATO, IDCLIENTE) VALUES (1,7);

insert into CONTRATOSCLIENTES (IDCONTRATO, IDCLIENTE) VALUES (2,6);

insert into CONTRATOSCLIENTES (IDCONTRATO, IDCLIENTE) VALUES (3,13);
insert into CONTRATOSCLIENTES (IDCONTRATO, IDCLIENTE) VALUES (3,1);

insert into CONTRATOSCLIENTES (IDCONTRATO, IDCLIENTE) VALUES (4,2);

insert into CONTRATOSCLIENTES (IDCONTRATO, IDCLIENTE) VALUES (5,10);