INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('Lavanderia', 15000);
INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('Porteria', 10000);
INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('TV por cable', 17000);
INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('Piscina', 5000);
INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('Jacuzzi', 10000);
INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('Wifi', 0);
INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('Agua caliente', 0);
INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('Cocina', 8000);
INSERT INTO SERVICIOS (DESCRIPCION, COSTOEXTRA) VALUES ('Recepcion 24 hrs', 3000);