NSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (7,1);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (8,1);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (3,1);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (7,5);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (8,5);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (3,5);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (1,2);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (6,2);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (2,2);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (3,2);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (1,3);
INSERT INTO SERVICIOSOFRECIDOS (IDSERVICIO, IDALOJAMIENTO) VALUES (6,3);
INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (2,1);
INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (6,1);
INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (9,1);
INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (1,1);

INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (3,2);

INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (1,3);
INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (2,3);
INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (9,3);

INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (2,4);
INSERT INTO SERVICIOSCONTRATADOS (IDSERVICIO, IDCONTRATO) VALUES (6,4);
